# Generated by Django 4.2.4 on 2023-08-05 14:46

from django.db import migrations, models
import utils.validate_image


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assests/img/%Y/%m/', validators=[utils.validate_image.validate_png]),
        ),
    ]
